#! /bin/bash

echo "\e[38;5;222m\nRemoving all scripts:\e[0m"

echo "\e[38;5;222mUninstalling Oh-My-Zsh.\e[0m"
sh $HOME/.oh-my-zsh/tools/uninstall.sh

if [ -x "$(command -v apt)" ]; then
	echo "\e[38;5;222mUninstalling ZSH with Apt.\e[0m"
	sudo apt purge zsh
elif [ -x "$(command -v pacman)" ]; then
	echo "\e[38;5;222mUninstalling ZSH with Pacman.\e[0m"
	sudo pacman -Rs zsh
elif [ -x "$(command -v yum)" ]; then
	echo "\e[38;5;222mUninstalling ZSH with Yum.\e[0m"
	sudo yum remove zsh
else
	echo -e "\n\e[31m\e[1mUnrecognised system!\e[0m"
	echo ""
	exit 1
fi
echo "\e[38;5;222mDeleting Bin directory.\e[0m"
rm -rf $HOME/bin
exit 0
